[BE] 리뷰 요청
codesquad-member-2020/todo-11 pull request #28
Opened 2020-04-06 19:33 UTC by Hyune-c

# 질문
- Notes table create 시 ID 를 int 타입으로 auto_increment 를 주었습니다
하지만 이전에 ID 는 LONG 형태로 하라고 했던 것이 기억나 LONG 으로 하려고 했더니 mysql 의 auto_increment 는 LONG 을 지원하지 않는다고 합니다
하여 그냥 INT 로 만들었는데 이것이 올바르게 한 것일까요?
- Spring JDBC 를 사용하라고 하셨는데 CrudRepository 를 extend 하고 필요한 메소드에 대하여 @Query 를 통해 쿼리를 만들면 되는 것일까요?
- DB 를 하다 쿼리가 제대로 실행되지 않아 찾아보니 대소문자가 구분 되는 것이 기본값이기 때문이었습니다
검색해보니 대소문자를 무시할 수 있는 설정도 있다고 하는데 어떻게 하는게 좋은 것일까요?
  - 모두 대문자
  - 모두 소문자
  - 설정을 통해 대소문자 구별이 없게 만듬

# 이후 구현 계획
- FE, iOS 의 테스트 지원을 위해 API 를 빠르게 만들었습니다
따라서 이후에는 Service, DAO, DTO 를 좀 더 공부하여 이를 적용할 계획입니다
  - 이미 DB 에 constraint 를 걸기는 했지만 bean validation 을 추가로 적용할 계획입니다
- intercepter 를 활용하여 pre 에는 로그인 체크를, post 에는 history 추가를 넣을 계획입니다

2020-04-07 07:26 UTC, Hyune-c commented
GET /api/notes/columns
POST /api/note
DELETE /api/note

기능 구현이 완료되어 추가 commit 하였습니다.

2020-04-07 13:32 UTC, Hyune-c commented
Service 를 통해 Controller 로직을 분리하였습니다
interface 접목을 통해 좀 더 깔끔한 코드를 의도했지만,  공통으로 묶을만한 부분을 찾지 못해 일단 개개의 Service 로 분리만 하였습니다.

2020-04-07 14:46 UTC, wheejuni requested changes
코드 작성하시느라 수고 많으셨습니다! 
과정 초반에 리뷰드렸던 내용들이 지켜지지 않은 부분이 있네요. 조금만 더 신경써 주세요. 

아래에 질문 답변내용 첨부해 드립니다.

1. 코멘트 통해 답변드렸습니다.
2. `@Query` 사용하시는 건 좋은데, Spring Data JDBC가 지원하는 query method convention 최대한 활용해보세요. -> 아 이거 지원 안하는군요 ㅋㅋ ㅠㅠ 죄송합니다 제가 혼동을.... `@Query` 많이 사용해주세요. 

3. `DB 를 하다 쿼리가 제대로 실행되지 않아` -> 쿼리가 의도하지 않은 결과를 뱉어냈다고 해석됩니다만, 어디서 쿼리를 실행한 결과인가요? Spring App 상에서요? 아니면 MySQL Workbench 같은 도구에서도 그런가요? 
'대소문자가 구분 되는 것이 기본값이기 때문이었습니다' -> 마찬가지로 DBMS상에서의 구분인지, 아니면 Spring Component 상에서의 구분인지요. 
'검색해보니 대소문자를 무시할 수 있는 설정도 있다고 하는데' -> 질문 중에 검색에 대해 언급하실 때는 검색 결과로 튀어나온 페이지 링크 몇 개를 첨부해주시는 것이 같이 고민하는 과정에 도움됩니다. 이 또한 마찬가지로, DBMS 상에서의 collation과 같은 설정인지, 아니면 Spring App 상에서 조정할 수 있는 설정인지 알기 힘드네요. 
따라서 이 질문은 도와드리기 살짝 어려울 것 같습니다. 아쉽습니다 ㅠ

4. 우선 첨부해주신 JSON은 `SELECT` 쿼리의 결과물로 나온 것이 아닌, Spring MVC controller가 만들어준 결과물로 보여집니다. 
Spring MVC가 JSON 형태의 결과물을 만들어 줄 때 Jackson이라는 라이브러리를 사용하므로, 해당 라이브러리가 boolean type의 필드명을 어떻게 처리하는지, 또 필드명을 사용자 정의하려면 어떤 설정을 해야하는지 정도로 방향잡으시고 조금만 더 구글링 & 고민 하시면 아주 쉽게 해결책을 찾으실 것 같아요.

충분한 답변이 되었기를 바라고요, 추가 질문 있으시면 언제든지 남겨주세요! 감사합니다.

2020-04-07 14:46 UTC, wheejuni commented on src/main/java/com/codesquad/todo/bean/ApiResponse.java
> +  private ApiResponse() {
빈 블록 중괄호 `'{}'` 한 줄로 붙여주세요..

2020-04-07 14:46 UTC, wheejuni commented on src/main/java/com/codesquad/todo/bean/Note.java
> +    isDeleted = true;
자기 필드에 메소드에서 접근할 때는 `this` 키워드를 사용하는게 어떨까요? 
그 편이 더 직관적이라고 보는데, 다른 의견이시면 말씀해주세요.

2020-04-07 14:46 UTC, wheejuni commented on src/main/java/com/codesquad/todo/config/SwaggerConfig.java
> +        .description("Todo-11 Api made by Dan")
ㅋㅋㅋ 자부심 좋습니다

2020-04-07 14:46 UTC, wheejuni commented on src/main/java/com/codesquad/todo/controller/AuthController.java
> +  AuthService authService;
접근제어자를 붙여 주십시오.

2020-04-07 14:46 UTC, wheejuni commented on src/main/java/com/codesquad/todo/controller/CoulumController.java
> +  CoulumService coulumService;
여기도 접근제어자를 붙여 주십시오.

2020-04-07 14:46 UTC, wheejuni commented on src/main/java/com/codesquad/todo/controller/CoulumController.java
> +public class CoulumController {
오타 있네요. `ColumnController` 가 맞는 표기입니다.

2020-04-07 14:46 UTC, wheejuni commented on src/main/java/com/codesquad/todo/controller/NoteController.java
> +  NoteService noteService;
여기도 접근제어자 부탁드려요.

2020-04-07 14:46 UTC, wheejuni commented on src/main/java/com/codesquad/todo/controller/NoteController.java
> +        (new ApiResponse(SuccessMessages.SUCCESS, noteService.deleteNote(id)), HttpStatus.OK);
꼭 두 줄로 개행할 이유가 없다면, 붙여서 써 주세요. 
아니면 소괄호를 열고 개행하는 것도 방법입니다. 
```
return new ResponseEntity<>(
    new ApiResponse(....
```
이런 식으로요.

2020-04-07 14:46 UTC, wheejuni commented on src/main/java/com/codesquad/todo/repository/NoteRepository.java
> +  @Query("select note.id, note.column_name, note.content, note.created_at, note.updated_at, note.writer from note where column_name = :columnName")
`@Query` 안에 들어가는 쿼리 SQL 코딩 컨벤션에 맞춰주면 가독성이 한결 좋아집니다. 
그리고 IDE의 도움으로 문자열 안에서 엔터를 치면 자동으로 문자열 연산기호로 치환되므로 이 방식을 통해 가독성을 확보해주세요. 
`SELECT`, `FROM`, `WHERE` 등 절이 한 번 바뀔 때마다 개행해주는 것이 SQL 쿼리의 가독성에 좋습니다. 
https://overoid.tistory.com/5 문서 참고해 주십시오.

2020-04-07 14:46 UTC, wheejuni commented on src/main/java/com/codesquad/todo/service/CoulumService.java
> +  NoteRepository noteRepository;
왜 모든 `@Autowired` 필드에 접근제어자를 생략하신 거죠

2020-04-07 14:46 UTC, wheejuni commented on src/main/java/com/codesquad/todo/service/NoteService.java
> +    result.put("notes", noteRepository.findAll());
이렇게 하나의 고정 필드에 여러 값을 매핑시키는 구조라면,
`Map` 을 활용하는 것보단 별도의 DTO class를 설계하는 구조가 더 나아보이기는 합니다.

2020-04-07 14:46 UTC, wheejuni commented on src/main/java/com/codesquad/todo/service/NoteService.java
> +    Note note = noteOptional.get();
`Optional` 에서 `.get()` 을 호출하는 것은 지양해주세요. 라는 리뷰를 초기부터 지금까지 계속 해드리고 있죠. ㅎㅎ
위험하고, 옵셔널답지 않은 사용법이므로 지양해 주세요.
참고로 이건 Optional을 다룰 수 있는 언어라면 모든 언어에서 다 공통적으로 권하는 사항이기도 합니다.
옆동네 Swift에서는 force unwrapping을 지양하라는 리뷰 코멘트를 자주 볼 수 있을 겁니다. 같은 의미입니다.

2020-04-07 14:46 UTC, wheejuni commented on src/main/resources/schema.sql
> +drop table if exists note;
앞선 코멘트에 공유드린 링크에서도 다루는 내용입니다만 SQL 사용하실 때 필드명, 테이블명 같은 고유명사성 키워드 제외하면 모두 대문자로 작성하시는 것이 일종의 컨벤션입니다.

2020-04-07 14:46 UTC, wheejuni commented on src/main/resources/schema.sql
> +    id          int           not null auto_increment,
`BIGINT` 로 설계하시면 Java의  `long` 타입과 상성이 맞습니다.

2020-04-07 14:46 UTC, wheejuni commented on src/main/resources/application.properties
> +spring.datasource.password=dan
어떤 경우에서도 Git으로 형상관리되는 파일에 **패스워드 노출하시면 안됩니다.** 
이 값을 여기에 부여하지 않고도 받아올 수 있는 다른 방법 고민해주세요.

2020-04-07 15:30 UTC, Hyune-c commented on src/main/java/com/codesquad/todo/bean/Note.java
> +    isDeleted = true;
사실 저는 this 사용을 선호하는 편이었는데, 저번 페어와 하다보니 그분은 this 사용을 안하는 것이 좋다는 의견을 주시더라구요 
딱히 반박할만한게 없어서 이후에는 생성자는 this 를 쓰지만 일반 메소드에서는 안쓰고 있었습니다

혹시 이것도 표준이라고 할만한게 있을까요..?

2020-04-07 15:32 UTC, Hyune-c commented on src/main/java/com/codesquad/todo/controller/NoteController.java
> +        (new ApiResponse(SuccessMessages.SUCCESS, noteService.deleteNote(id)), HttpStatus.OK);
자동 정렬을 자주하다보니까 생긴것 같아요
괄호를 열고 개행하는 방법으로 개선하겠습니다

2020-04-07 15:33 UTC, Hyune-c commented on src/main/java/com/codesquad/todo/repository/NoteRepository.java
> +  @Query("select note.id, note.column_name, note.content, note.created_at, note.updated_at, note.writer from note where column_name = :columnName")
감사합니다. 링크를 보고 공부해보겠습니다

2020-04-07 15:33 UTC, Hyune-c commented on src/main/java/com/codesquad/todo/service/CoulumService.java
> +  NoteRepository noteRepository;
복붙하다보니 까먹은거 같아요.. 수정하겠습니다 ㅠ

2020-04-07 15:36 UTC, Hyune-c commented on src/main/java/com/codesquad/todo/service/NoteService.java
> +    result.put("notes", noteRepository.findAll());
말씀하신거처럼 DTO Class 를 구성하면 거기에 맞는 것만 들어갈 수 있지 않나요?
value 값으로 Note 가 들어가야될 때도 있고, String 이 들어가야될 때도 있어서 저렇게 만들었었습니다

혹시 그 모든 것을 담은 DTO 를 만들어야 된다는 뜻일까요?

2020-04-07 15:37 UTC, Hyune-c commented on src/main/java/com/codesquad/todo/service/NoteService.java
> +    Note note = noteOptional.get();
넵. 이부분은 인지하고 있었지만 Execption 을 처리할 때 만들려고 했었습니다 
(orElseThrow 시 넣은 Execption 이 아직 없는 상태라..)

다음 리뷰 요청시에는 개선하여 올리도록 하겠습니다

2020-04-07 15:39 UTC, Hyune-c commented
@wheejuni 리뷰 감사합니다!

2020-04-08 04:54 UTC, Hyune-c commented on src/main/java/com/codesquad/todo/service/NoteService.java
> +    result.put("notes", noteRepository.findAll());
Object 가 아닌 Generic 을 사용하면 될 것 같다는 생각을 하였습니다.
하지만 아직 접목하기에는 이해가 부족해서 당장은 힘들 듯 합니다.. ㅠ

2020-04-08 04:57 UTC, Hyune-c commented
dev -> be-review 로 PR 을 보내다보니 FE 의 것들도 같이 보이는 것 같습니다
다음 PR 부터는 BE 것만 보일 수 있도록 branch 를 조정하겠습니다

2020-04-08 09:11 UTC, Hyune-c commented
잘못된 branch 로 설정으로 인해 다른 클래스 것이 보이고 있습니다
정리된 branch 로 다시 PR 올리겠습니다

2020-04-08 09:11 UTC, closed without merging