[BE] 리뷰 요청
codesquad-member-2020/todo-11 pull request #81
Opened 2020-04-16 09:09 UTC by Hyune-c

## 구현된 기능
- 기본 요구 기능 모두 구현 
- jwt 인증
  - interceper 사용
  - FE, iOS 의 준비가 되지 않아 예외 처리는 주석 표시
- jtw 를 통한 멀티유저 기능
- 초기 데이터를 넣음에 있어 sql 파일을 읽는 대신 메소드 검증도 하기 위해 호출 형태를 하였습니다 

## 추가 구현 예정
- 비밀번호 외부 참조로 변경

## 인지하고 있지만 고치기 힘든 것
- 설계 당시 aggregation 개념을 정확히 잡지 못해 OOP 에서 벗어난 설계로 모든 객체들이 repository 를 가지고 있습니다
- @Transactional 어노테이션을 잘 쓰고 있는 것인지 모르겟습니다
- history 구현
  - 현재는 interceptor 의 afterCompletion 에서 이루어지고 있는데, 비지니스 로직과 인프라 로직의 차이를 정확히 알지 못해 잘못 넣었습니다  
구현을 완료한 지금에서는 Service 단에서 끝냈어야 된다고 생각합니다
  - history 기록을 위해 requestBody 가 필요한데, 이미 읽는 것이 끝난 stream 을 가져오는 법을 좋은 방법으로 구현하지 못했습니다  
Wrapper 를 사용하는 것이 좋다는 것까지는 찾았지만 적용을 하는 것에는 실패하였습니다
- @Autowired 를 사용함에 있어 생성자 DI 를 사용하는 것이 더 좋지만, 사용하는 과정에서 Bean configuration 을 제대로 하지 못하여 일관성 있는 사용을 하지 못했습니다

## 질문
- Service 를 구현함에 있어 Generic 을 사용하였습니다
길이는 짧아졌지만, Object 를 사용함과 큰 차이를 느끼지 못하겠는데 제대로 한 것이 맞을까요?

2020-04-25 06:37 UTC, wheejuni requested changes
코드 작성하느라 수고 많으셨어요. 
다만 반복적으로 계속 같은 수정사항을 지적드리게 되는 점은 좀 아쉽네요. 

아래에 질문하신 것 답변 드릴게요. 
1) 서비스 클래스들에 대한 코멘트로 답변이 충분히 되었기를 바랍니다. 
2) 같이 한 번 해볼까요? 오늘 오세요?

2020-04-25 06:37 UTC, wheejuni commented on src/main/java/com/codesquad/todo/TodoApplication.java
> +    restTemplate.execute("http://localhost:8080/dev-api/init", HttpMethod.GET, null, null);
컨텍스트 밖에서 이런 코드를 실행하는 이유는 무엇인가요? 
잘 작동하나요?

2020-04-25 06:37 UTC, wheejuni commented on src/main/java/com/codesquad/todo/bean/ApiResponse.java
> +  private Map<String, ?> contents;
제네릭과 와일드카드 파라미터에 대해 좀 더 학습해보고 적용할 것을 권합니다. 
짐작하기로는 `ApiResponse<T>` 와 같은 객체를 생성하고, 해당 타입을 Map의 밸류 타입으로 받을 수 있게끔 구상한 것 같은데요, 
관련한 개념을 좀 더 깊게 학습해보고 이 클래스를 다시 설계해 보길 권합니다.

2020-04-25 06:37 UTC, wheejuni commented on src/main/java/com/codesquad/todo/bean/Note.java
> +  public Note() {
빈! 중괄호는! 한 줄에 써주세요. ㅠㅠ

2020-04-25 06:37 UTC, wheejuni commented on src/main/java/com/codesquad/todo/bean/Note.java
> +  {
중괄호 이런 스타일로 선언하는 것은 C-style입니다. 
Java 컨벤션에 맞게 선언해주세요.

2020-04-25 06:37 UTC, wheejuni commented on src/main/java/com/codesquad/todo/controller/CategoryController.java
> +    request.setAttribute("body", category);
body에 쓰지 않고 attribute로 처리한 다른 이유가 있을까요?

2020-04-25 06:37 UTC, wheejuni commented on src/main/java/com/codesquad/todo/controller/NoteController.java
> +    request.setAttribute("body", note);
`response` 가 아닌 `request` 였군요, 혹시 의도한 바가 어떤 건가요?

2020-04-25 06:37 UTC, wheejuni commented on src/main/java/com/codesquad/todo/interceptor/Interceptor.java
> +public class Interceptor extends HandlerInterceptorAdapter {
클래스 이름 지으실때 `Interceptor` 와 같이 지나치게 일반적인 명칭은 사용 자제해주세요.

2020-04-25 06:37 UTC, wheejuni commented on src/main/java/com/codesquad/todo/interceptor/Interceptor.java
> +}
아직 컨벤션이 손에 익지 않았다면, IDE 도구의 도움을 받아보는 것도 괜찮을 것 같아요. 
https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html 참고해보세요.

2020-04-25 06:37 UTC, wheejuni commented on src/main/java/com/codesquad/todo/service/BasicService.java
> +public class BasicService {
서비스 패키지 구조를 잡음에 있어 상속을 무조건 지양해야 하는 것은 아닙니다만, 이런 방식의 상속 사용은 한번 더 생각해보시기를 권해드리고 싶습니다.

지금 `BasicService` 의 역할을 보면 단순히 `protected` 메소드에서 서비스 클래스가 처리한 결과값을 맵으로 매핑해주는 역할밖에 하지 않고 있습니다. 
이런 역할은 별도의 Util 클래스나 각 서비스 클래스의 로직 중간에 위치해도 그렇게 나쁜 코드가 아니라고 보여집니다. 
오히려 이런 방식의 상속은 불필요한 사이드 이펙을 초래할 여지도 있습니다. 
예를 들어 

```java
@Autowired 
private List<BasicService> services
``` 

와 같은 의존성 주입도 가능해지게 될텐데요, 이건 의도한 효과인가요? 
서비스에서 상속관계를 가질때는 다루는 도메인이 같은 두 개 이상의 로직을 가질 때만 그렇게 하셨으면 좋겠습니다. 

예를 들어... 회원들에게 알림을 보내는 서비스 클래스를 구현한다고 가정해 봅시다. 
비즈니스가 확장됨에 따라 처음엔 SMS만 쐈지만, 나중엔 카카오 알림톡도 쏘고, 네이버 톡톡도 쏘고, 페메도 보낼 수 있겠죠. 그럼 아래와 같은 타입을 정의하고 점진적인 확장을 추구하는 것이 좋습니다. 

```java 
public interface NotifyService {
    void notify(List<User> users);
}

public class SMSNotifyService implements NotifyService 
public class KakaoTalkNotifyService implements NotifyService
public class NaverTalkNotifyService implements NotifyService 

...
```

제가 제시해드린 개념에 관해서, https://woowabros.github.io/study/2018/03/05/sdp-sap.html 좋은 글이 있으니 링크 타고 한번 읽어보시고, 다음 서비스 클래스를 설계할 때에 도움이 되길 바랍니다.

2020-04-25 06:37 UTC, wheejuni commented on src/main/java/com/codesquad/todo/service/CategoryService.java
> +    return getResultMap("category", categoryRepository.findAll());
상속 구조를 사용함으로 해서 중복 코드는 일정 부분 줄였을지 모르겠습니다만, 
제네릭에 이 서비스에 맞는 타입 파라미터를 못 넣음으로 인해 이걸 받아쓰는 다른 사용처 클래스들에선 다른 부가 작업이 필요하게 되는 결과를 초래했습니다(캐스팅 등).

2020-04-25 06:37 UTC, wheejuni commented on src/main/java/com/codesquad/todo/service/DevService.java
> +  public void init() {
init성 코드는 `CommandLineRunner` 의 구현체로 하거나, 별도의 SQL 파일을 만들어서 해 주세요.

2020-04-25 06:37 UTC, wheejuni commented on src/main/java/com/codesquad/todo/service/HistoryService.java
>    public void create(HttpServletRequest request) {
service layer에서 presentation layer에 고립돼야 할 클래스 참조하지 않도록 해주세요.

2020-04-25 06:37 UTC, wheejuni commented on src/main/java/com/codesquad/todo/service/HistoryService.java
> +        .append("}");
어...뭘 하고 싶었던 거죠? 
대략 짐작해보면... 칼럼 하나에 여러 값을 넣기 위해서? 혹은...음....
데이터베이스의 정규화를 통해 풀어야 할 문제를 너무 rough하게 접근한 것은 아닌지 한번만 더 고민해주세요. 

물론 실무에서도....이런식으로 DB에 때려박는 구현을 많이 하는 건 사실입니다. 
이전 회사에서도, 지금 회사에서도 이런 식의 포맷을 가진 칼럼이 적어도 열 개 이상은 있는 것 같군요. 
그래도 아직 우리는 공부하는 단계이고, 베스트 프랙티스에 대해 고민할 여유가 있으니까 다른 방법을 고민해보면 어떨까요.

2020-04-25 06:37 UTC, wheejuni commented on src/main/java/com/codesquad/todo/service/HistoryService.java
> +  private String getBody(HttpServletRequest request) {
`Controller` 에서 request에 굳이 애트리뷰트를 셋 한 이유가 여기에 있었네요. 
DTO가 필요하면 별도의 DTO 클래스를 구현하시고 **절대로 `HttpServletRequest` 를 DTO 성격으로 사용하지 않기를 바랍니다.**

2020-04-26 00:10 UTC, Hyune-c commented on src/main/java/com/codesquad/todo/TodoApplication.java
> +    restTemplate.execute("http://localhost:8080/dev-api/init", HttpMethod.GET, null, null);
초기 데이터를 sql 이 아닌 내부 메소드를 통해서 만들기 위해 실행했습니다

2020-04-26 00:14 UTC, Hyune-c commented on src/main/java/com/codesquad/todo/controller/CategoryController.java
> +    request.setAttribute("body", category);
interceptor 를 사용함에 있어서 값을 전달해주어야 되는데 model 을 사용하지 않고는 방법을 찾지 못하여 사용하였습니다

2020-04-26 00:15 UTC, Hyune-c commented on src/main/java/com/codesquad/todo/controller/NoteController.java
> +    request.setAttribute("body", note);
interceptor 를 사용함에 있어서 값을 전달해주어야 되는데 model 을 사용하지 않고는 방법을 찾지 못하여 사용하였습니다

2020-04-26 00:17 UTC, Hyune-c commented on src/main/java/com/codesquad/todo/service/BasicService.java
> +public class BasicService {
협업을 위해 공통된 부분을 interface 등으로 뺴려는 의도였는데 올바르게 사용하지 못한듯 합니다
현재 진행 중인 프로젝트에는 공통util 로 뺴서 처리하고 있습니다

2020-04-26 00:18 UTC, Hyune-c commented on src/main/java/com/codesquad/todo/service/CategoryService.java
> +    return getResultMap("category", categoryRepository.findAll());
좀 더 연습해보겠습니다 ㅠ

2020-04-26 00:19 UTC, Hyune-c commented on src/main/java/com/codesquad/todo/service/DevService.java
> +  public void init() {
CommandLineRunner 를 공부해보겠습니다

2020-04-26 00:33 UTC, Hyune-c commented on src/main/java/com/codesquad/todo/service/HistoryService.java
>    public void create(HttpServletRequest request) {
request 에 필요한 내용이 있는 경우, 필요한 내용만 파라미터로 받는 것이 좋은 방법일까요?

2020-05-19 07:44 UTC, honux77 commented on src/main/java/com/codesquad/todo/TodoApplication.java
> +    restTemplate.execute("http://localhost:8080/dev-api/init", HttpMethod.GET, null, null);
23일이 지났지만 이걸 꼭 그렇게 했어야 하는지 의문이네요. 다른 대안은 없었을까요?

2020-05-19 08:04 UTC, honux77 commented
수고하셨어요. 좋은 지적이 많은데 최근 코드에는 잘 반영이 되었으면 좋겠네요.

2020-05-19 08:04 UTC, merged